CREATE TABLE USER (
    ID INTEGER IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(128) NOT NULL,
    MIDDLE_NAME VARCHAR(16),
    LAST_NAME VARCHAR(128) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR(16) NOT NULL,
    CREATED_BY VARCHAR(200) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    LAST_MODIFIED_BY VARCHAR(200)NOT NULL,
    LAST_MODIFIED_DATE DATETIME NOT NULL
);